### PR TITLE
changed isRowEmpty function logic, it was working incorrectly 

### PR DESCRIPTION
**Pull request by tanveer-ali**
isRowEmpty function was not working correctly with multiple columns .. returning false on the first column emptycriteria not matched ... now isRowEmpty will return true if any column emptycriteria matched and false it all columns emptycriteria are false.

### CODE REVIEW

**Comment by hkalbertl** [comment]
Hi tanveer-ali,

Thanks for contribute in `appendGrid`!

Unfortunately, i guess I cannot accept your changes.
The `isRowEmpty` function is used to check all column values that are empty or not.

For example, I have a grid with three text column, no emptyCriteria is defined.
Now, I enter some text in the text box of second column.
So, this is not an empty row, right?

The `isRowEmpty` function is latest release will return false.
But your changes will return true because it found that the value of first column is empty and exit the function.

Feel free to let me know if there are something wrong or I misunderstood your changes.
Thanks!

**Comment by tanveer-ali** [comment]
Hi Albert,

I have modified the file again to accommodate the isrowempty logic if no emptycriteria is define, please check my changes ... the main reason I modified the file was  If emptycriteria is defined for more then 1 columns then all columns emptycriteria should be met before isRowEmpty return false ... currently it return true on 1st emptycriteria matched, ignoring the rest of the columns.

modified the isRowEmpty function so now if no emptycriteria is defined for a column that column will not be checked for empty logic, if all columns are set with no emptycriteria and all columns are empty then isrowempty will return true as we don't want complete empty rows.

Please check the file as I modified it three times and now its working for every case, as I have tested out.

Thanks

**Comment by hkalbertl** [comment]
Hi again,

I know you want to check all column values is empty now. But I still have concern on your changes:

1. `all columns emptycriteria should be met before isRowEmpty return false`
I guess it is not a good design in terms of performance. Current routine will check columns one by one. When first column is not empty, it is not required to check the others because this row is already not empty. One more example, if I have a big grid that has 10 columns and 100 rows with all filled with data. Your approach will run 100 x 10 checkings to identify the whole grid is not empty. But current routine will run 100 checkings only.

2. `currently it return true on 1st emptycriteria matched, ignoring the rest of the columns`
I don't thing the current routine will return true and exit. If first column is matched which means it is empty, appendGrid will continue check on the next column. (Check my sample jsfiddle below)

3. `if no emptycriteria is defined for a column that column will not be checked for empty logic`
emptyCriteria is an option that allow user to specify a value or a function to check their column values are empty or not. A default `isEmpty` checking logic will be applied when nothing is defined. This routine is over there since the first release of `isRowEmpty` feature so it is not good to remove it as some other users are using that.

4. I can see your latest changes still have the problem that I said in previous comment. When a function is defined in first column's `emptyCriteria` and it is matched (which is first column is empty), the routine will return true and exit without checking the other columns although they may be not empty.

I have created two jsfiddle for you to check. Both of them have the same HTML and JS code, but one of them is using the latest `appendGrid` and the other one is using your modified version.
Latest appendGrid: http://jsfiddle.net/hkalbertl/6djL2t92/
Your version: http://jsfiddle.net/hkalbertl/x1stwesk/

May be I still cannot understand was you want. Can you give me a real case sample (source code / jsfiddle / etc.) that shows your problem and what you expected? Thanks!

**Comment by tanveer-ali** [comment]
Hey I had made one more change .. but did not commit .. you can check that
out ...
I have custom add row button and i add a row after checking the empty row
condition .. anyways it is working fine with this new commit ..


check this again for empty criteria functions for first 2 columns, the
third row isrowempty is false , however column B still has value 'B' , for
me I need emptycriteria in all columns in a row should be false then the
row can be declared not empty.

check this again .. updated
http://jsfiddle.net/6djL2t92/8/






Tanveer Ali | Software Developer
Assent Compliance Inc. | www.AssentCompliance.com
<http://www.assentcompliance.com/>
Direct: 613-709-3517 | 1-866-964-6931
tanveer.ali@assentcompliance.com
[image: cid:7FE7D2C3-84A2-442D-B099-0737AC7F8FEA]
Check out our Regulatory Success Center
<http://www.assentcompliance.com/supplier-success-center/> and Blog
<http://assentcompliance.com/blog/>

**Comment by hkalbertl** [comment]
Hi,

The jsfiddle in your last comment is referencing to my latest release.
So, I copied your JS changes to another jsfiddle and I still got the same problem (the 4th issue) as said in my previous comment: http://jsfiddle.net/x1stwesk/7/

` for me I need emptycriteria in all columns in a row should be false then the
row can be declared not empty.`
Let me ask a question first. I have a grid with three columns. All of them have a emptyCriteria function defined. This is the behavior of latest `appendGrid`:

|  | Col A empty | Col B empty | Col C empty  | isRowEmpty |
| ------------- | -------------| -------------| ------------- | ------------- |
| Case 1 | False | False | False | False | 
| Case 2 | True | False | False | False | 
| Case 3 | True | True | False | False | 
| Case 4 | True | True | True | True | 

So, it that you want the following behavior instead?

|  | Col A empty | Col B empty | Col C empty | isRowEmpty |
| ------------- | -------------| -------------| ------------- | ------------- |
| Case 1 | False | False | False | False | 
| Case 2 | True | False | False | True | 
| Case 3 | True | True | False | True | 
| Case 4 | True | True | True | True |

**Comment by tanveer-ali** [comment]
I want this behaviour which is false in current implementation you can test.



*Col A empty Col B empty Col C empty isRowEmpty*
Case 1 False True True True







Tanveer Ali | Software Developer
Assent Compliance Inc. | www.AssentCompliance.com
<http://www.assentcompliance.com/>
Direct: 613-709-3517 | 1-866-964-6931
tanveer.ali@assentcompliance.com
[image: cid:7FE7D2C3-84A2-442D-B099-0737AC7F8FEA]
Check out our Regulatory Success Center
<http://www.assentcompliance.com/supplier-success-center/> and Blog
<http://assentcompliance.com/blog/>

**Comment by tanveer-ali** [comment]
Also the following

4. I can see your latest changes still have the problem that I said in
previous comment. When a function is defined in first column's emptyCriteria
 and it is matched (which is first column is empty), the routine will
return true and exit without checking the other columns although they may
be not empty.


Yes it should be true because if any column empty criteria function defined
and it is empty so row should be empty. Row will only be not empty when all
empty criteria return false not just one of them .. that's what i want.






Tanveer Ali | Software Developer
Assent Compliance Inc. | www.AssentCompliance.com
<http://www.assentcompliance.com/>
Direct: 613-709-3517 | 1-866-964-6931
tanveer.ali@assentcompliance.com
[image: cid:7FE7D2C3-84A2-442D-B099-0737AC7F8FEA]
Check out our Regulatory Success Center
<http://www.assentcompliance.com/supplier-success-center/> and Blog
<http://assentcompliance.com/blog/>

**Comment by hkalbertl** [comment]
Hi,

I guess `isRowEmpty` and `emptyCriteria` is not you are looking for.
We have a different definition on `empty row`.

My implementation is when one of the column is NOT empty then it is NOT an empty row.

But in your case, any ONE of the columns is empty will consider as empty.

As I said before, the current implementation was released for a while so it is not a good idea to made this changes because this will affect all current users.

My suggestion is you better not to use the current empty checking logic (because it is not you wanted) and call another custom checking that fit your requirement as needed. For example:
```javascript
function customIsRowEmpty(rowIndex) {
  var data = $('#tblAppendGrid').appendGrid('getRowValue', rowIndex);
  if (data['colA'] != '???' || data['colB'] != '!!!' || data['colC'] != '***') {
    // Any one column is equal to specified `empty` value will consider as empty
    return true;
  } else {
    // All columns are matched to their empty value
    return false;
  }
}
```
And call this to loop through all rows
```javascript
var count =  $('#tblAppendGrid').appendGrid('getRowCount');
for (var i = 0; i < count; i++) {
  if (customIsRowEmpty(i)) {
    // Row is empty, do something?
  }
}
```
Can this solution / work around solve your problem?
Feel free to let me know if you have further questions.
Thanks!

**Comment by tanveer-ali** [comment]
Hi Albert,

I guess then I will use mine version for my project .. As I am also
using removeEmptyRows which is using the same isRowEmpty function to check
empty row and removin rows so let me use my version. Thanks for the
explanation, as we have a different definition on empty row.

Regards,
Tanveer






Tanveer Ali | Software Developer
Assent Compliance Inc. | www.AssentCompliance.com
<http://www.assentcompliance.com/>
Direct: 613-709-3517 | 1-866-964-6931
tanveer.ali@assentcompliance.com
[image: cid:7FE7D2C3-84A2-442D-B099-0737AC7F8FEA]
Check out our Regulatory Success Center
<http://www.assentcompliance.com/supplier-success-center/> and Blog
<http://assentcompliance.com/blog/>

**Comment by hkalbertl** [comment]
Thanks for your understanding.

For your information, there is a beta version of `appendGrid` that implemented table content scrolling feature. Feel free to try if you are interested :)

**Pull request closed without merging**
